runtime: nodejs20

service: default

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.6

handlers:
  # Serve static files
  - url: /(.*\.(gif|png|jpg|css|js|svg))$
    static_files: dist/\1
    upload: dist/(.*\.(gif|png|jpg|css|js|svg))$
    secure: always
    http_headers:
      Cache-Control: 'public, max-age=3600'

  # Serve main HTML file
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      X-XSS-Protection: '1; mode=block'
      Strict-Transport-Security: 'max-age=31536000; includeSubDomains'
      Cache-Control: 'no-cache'

env_variables:
  NODE_ENV: "production"
  VITE_API_URL: "https://backend-dot-edu-play-video.uc.r.appspot.com"