runtime: python39
entrypoint: gunicorn --timeout 60 -b :$PORT app.main:app

service: backend

instance_class: F2  # Upgraded for better performance

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  max_concurrent_requests: 50
  target_throughput_utilization: 0.6
  min_pending_latency: 30ms
  max_pending_latency: 100ms

env_variables:
  GOOGLE_CLOUD_PROJECT: "edu-play-video"
  FLASK_ENV: "production"
  GOOGLE_APPLICATION_CREDENTIALS: "edu-play-video-a86bb5e64eed.json"
  CORS_ORIGINS: "https://frontend-dot-edu-play-video.uc.r.appspot.com"

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
- warmup